language: python

python: "3.7"

install: pip install pkgcheck 

before_script:
    - sudo mkdir -p /etc/portage /var/cache/distfiles /var/db/repos/gentoo
    - sudo chmod a+rwX /etc/portage /var/cache/distfiles /var/db/repos/gentoo
    - wget -qO - "https://github.com/gentoo-mirror/gentoo/archive/stable.tar.gz" | tar xz -C /var/db/repos/gentoo --strip-components=1
    - wget "https://www.gentoo.org/dtd/metadata.dtd" -O /var/cache/distfiles/metadata.dtd
    - >
        printf "%s\n"
        '[DEFAULT]'
        'main-repo = gentoo'
        '[gentoo]'
        'location = /var/db/repos/gentoo'
        >/etc/portage/repos.conf
    - cat -A /etc/portage/repos.conf
script:
    - pkgcheck scan
